let books = [
    { ID: 1, Title: "The Catcher in the Rye", Author: "J.D. Salinger", Rating: 4.5, Genre: "Fiction" },
    { ID: 2, Title: "To Kill a Mockingbird", Author: "Harper Lee", Rating: 4.8, Genre: "Fiction" },
    { ID: 3, Title: "1984", Author: "George Orwell", Rating: 4.7, Genre: "Fiction" },
    { ID: 4, Title: "Brave New World", Author: "Aldous Huxley", Rating: 4.6, Genre: "Science" },
    { ID: 5, Title: "The Great Gatsby", Author: "F. Scott Fitzgerald", Rating: 4.3, Genre: "Fiction" },
    { ID: 6, Title: "Pride and Prejudice", Author: "Jane Austen", Rating: 4.9, Genre: "Romance" },
    { ID: 7, Title: "The Fault in Our Stars", Author: "John Green", Rating: 4.8, Genre: "Romance" },
    { ID: 8, Title: "The Time Traveler's Wife", Author: "Audrey Niffenegger", Rating: 4.5, Genre: "Romance" },
    { ID: 9, Title: "A Brief History of Time", Author: "Stephen Hawking", Rating: 4.7, Genre: "Science" },
    { ID: 10, Title: "The Theory of Everything", Author: "Stephen Hawking", Rating: 4.6, Genre: "Science" },
    { ID: 11, Title: "The Hobbit", Author: "J.R.R. Tolkien", Rating: 4.7, Genre: "Fiction" },
    { ID: 12, Title: "The Lord of the Rings", Author: "J.R.R. Tolkien", Rating: 4.9, Genre: "Fiction" },
    { ID: 13, Title: "Wuthering Heights", Author: "Emily Brontë", Rating: 4.6, Genre: "Romance" },
    { ID: 14, Title: "Dune", Author: "Frank Herbert", Rating: 4.8, Genre: "Science" },
    { ID: 15, Title: "The Hunger Games", Author: "Suzanne Collins", Rating: 4.5, Genre: "Fiction" },
    { ID: 16, Title: "The Alchemist", Author: "Paulo Coelho", Rating: 4.8, Genre: "Fiction" },
    { ID: 17, Title: "The Notebook", Author: "Nicholas Sparks", Rating: 4.4, Genre: "Romance" },
    { ID: 18, Title: "Fifty Shades of Grey", Author: "E.L. James", Rating: 4.2, Genre: "Romance" },
    { ID: 19, Title: "The Martian", Author: "Andy Weir", Rating: 4.8, Genre: "Science" },
    { ID: 20, Title: "A Wrinkle in Time", Author: "Madeleine L'Engle", Rating: 4.6, Genre: "Science" },
    { ID: 21, Title: "The Picture of Dorian Gray", Author: "Oscar Wilde", Rating: 4.5, Genre: "Fiction" },
    { ID: 22, Title: "The Secret Garden", Author: "Frances Hodgson Burnett", Rating: 4.7, Genre: "Fiction" },
    { ID: 23, Title: "Jane Eyre", Author: "Charlotte Brontë", Rating: 4.9, Genre: "Romance" },
    { ID: 24, Title: "The Help", Author: "Kathryn Stockett", Rating: 4.7, Genre: "Fiction" },
    { ID: 25, Title: "The Fault in Our Stars", Author: "John Green", Rating: 4.8, Genre: "Romance" },
    { ID: 26, Title: "The Road", Author: "Cormac McCarthy", Rating: 4.2, Genre: "Fiction" },
    { ID: 27, Title: "The Science of Interstellar", Author: "Kip Thorne", Rating: 4.6, Genre: "Science" },
    { ID: 28, Title: "Atlas Shrugged", Author: "Ayn Rand", Rating: 4.3, Genre: "Fiction" },
    { ID: 29, Title: "Ender's Game", Author: "Orson Scott Card", Rating: 4.7, Genre: "Science" },
    { ID: 30, Title: "The Rosie Project", Author: "Graeme Simsion", Rating: 4.6, Genre: "Romance" }
];
export default books;
